redis.url: "redis://h:pab3ed074b2a3be45f2ed8602408c05d68466eee13a641eedd8209ff87818f7f3@ec2-34-252-120-111.eu-west-1.compute.amazonaws.com:49919"
config.key: statistics-service

spring.data.mongodb.host: ds223009.mlab.com
spring.data.mongodb.port: 23009
spring.data.mongodb.database: heroku_z4wd2s19
spring.data.mongodb.username: heroku_z4wd2s19

application.security.secret: "top-secret"

#logging
logging.level.org.springframework.data: debug
logging.level.: info

